### ISSUE TITLE
Changes Required

### ISSUE THREAD

**Issue by anyars-encarta** [the-faizmohammad/Capstone-API-based-webapp#24]
Great work so far on this milestone! 👏 There are, however, some repetitions in your CSS you need to address to make your code DRY!

In your code, you:

```
nav {
 display: flex;
}
```

```
.container {
 display: flex;
}

```
```
.card-buttons {
 display: flex;
}
```

I think it will be better you use:

```
nav,
.container,
.card-button {
display: flex;
}
```
<img src="https://media3.giphy.com/media/tmWDjWCjGbewYKCurl/giphy-downsized-medium.gif"/>

**Comment by the-faizmohammad** [comment]
Thank you so much for your great feedback 🤗.
